### ISSUE TITLE
QNIC-based, fully blocking circuit switching

### ISSUE THREAD

**Issue by rum-yasuhiro** [sfc-aqua/quisp#55]
## The goal

Fully blocking circuit switched resource allocation with released random backoff on failure
in order to avoid `dead lock`

## Tasks
- [x] Add to "Q node" ( or "QNIC" ) "Allocated" flag.
- [x] modify Connection manager to handle massage to test and set allocated flag
""" Example pseudo code
if(! allocated){
    allocate
    ( continue processing )
}else{
    send reject request
    ( about processing )
}
"""

- [x] define reject setup request message type

- [x] Connection manager :: handle massage extend to handle
""" Example pseudo code
Reject:
    Allocated -> False
"""

- [x] random backoff
"""
if ( EndNode ): 
    sleep( random ) // send yourself a message to the future
    try again 
"""" 

- [ ] Limit the lifetime of a connection 
    - set the parameter for that.

- [ ] Implement connection tear down
    - Do we need new message type?
    - clear allocated flag

**Comment by rdviii** [comment]
A couple of useful comments over at #24, but probably outdated now.
Notes available at
https://hackmd.io/ruP6-gCmQh6zoApdXz8DRw?view

**Comment by rdviii** [comment]
Looks pretty awesome!

One problem: if I'm interpreting the animation right, QNIC reservations are only created on the _receiving_ QNICs. However, both the inbound and outbound QNICs need to be reserved. Otherwise, two requests that are going in opposite directions on the same link could wind up double-reserving the link.

**Comment by rdviii** [comment]
![image](https://user-images.githubusercontent.com/2833100/77807743-19fef500-70cc-11ea-8082-6cb04da110d9.png)

ConnectionRequests from EndNodes 3, 4, and 5 all pass through Router2, all planning to use the Router2-->Router1 link.  But the Reject message comes from Router1, when it ought to be from Router2.

**Comment by Chibikuri** [comment]
I think, 
we have connections
node3 <---> router2 port1
node4 <---> router2 port2
node5 <---> router2 port3
So, when the request goes to router2, it's fine. All end nodes will be accepted.
But when packet goes to router1,
router2 port4 <----> router1 port1
there is only one connection it can establish.
So, we have to choose one of three connections from above.

**Comment by rdviii** [comment]
Yes, the bottleneck is the link router2<-->router1 link, but *router2* should recognize that and reject two of the connections.  The problem is that the rejection seems to be coming from Router1.

With timestamps (upper right corner):

![image](https://user-images.githubusercontent.com/2833100/77812828-5e4bbe80-70e7-11ea-8ee8-8fe84a73582f.png)
![image](https://user-images.githubusercontent.com/2833100/77812837-79b6c980-70e7-11ea-996e-f07e09110431.png)
![image](https://user-images.githubusercontent.com/2833100/77812858-9f43d300-70e7-11ea-8887-4771f55ab898.png)
![image](https://user-images.githubusercontent.com/2833100/77812880-bedafb80-70e7-11ea-824b-e9ae93c376ed.png)

**Comment by Chibikuri** [comment]
Close this issue and make issues for left things.
